### ISSUE TITLE
Add golang, rust, v8, openjdk to tracking page.

### ISSUE THREAD

**Issue by lazyparser** [riscv/riscv-toolchains-runtimes#2]
The golang, Rust, V8, OpenJDK are important toolchains & runtines. They are under the cover of T&R HSC.

**Comment by cmuellner** [comment]
Yes, we should keep track of them.
V8 and OpenJDK will later be handed over to the managed runtimes TG.

**Comment by cmuellner** [comment]
All mentioned languages/runtimes are now listed here:
https://github.com/riscv/riscv-toolchains-runtimes/blob/master/monitoring/languages.adoc

**Comment by cmuellner** [comment]
We have now a RISC-V status of GHC, Go, OpenJDK, PHP, Rust and V8.
Thus, I will close this issue.
Thanks for reporting!
