### ISSUE TITLE
Should we separate the Bitmanip extension into Zb* pieces?

### ISSUE THREAD

**Issue by lazyparser** [riscv/riscv-toolchains-runtimes#3]
Seems the Bitmanip has different parts, which have different ratify process.

**Comment by vineetgarc** [comment]
You are referring to the already ratified : Isn't it already fine-grained: Zba, zbb, zbc, zbs ?

**Comment by cmuellner** [comment]
I think we can close this, given specification is ratified and patches are upstream.
